---
galaxy_info:
  author: "Dmitrii Kashin"
  description: "Manage cron jobs"
  role_name: cron
  license: MIT
  min_ansible_version: "2.10"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - cron
allow_duplicates: true
dependencies: []
...
