---
- block:
    - name: create file by template file
      ansible.builtin.template:
        src: "{{ template_src }}"
        dest: "{{ template_dest }}"
      register: template_result
  when: template_src is defined

- block:
    - name: create file by inline template
      ansible.builtin.copy:
        content: "{{ template_content }}"
        dest: "{{ template_dest }}"
      register: template_result
  when: template_content is defined
...
