---
- name: "{{ pip_install_task_prefix }} Install pip"
  ansible.builtin.include_role:
    name: ru-ops.general.pkg_install
  vars:
    pkg_install_packages:
      - python3-pip
      - python3-setuptools
  when:
    - ansible_distribution | default('none') in [ 'Ubuntu', 'Debian', 'Astra Linux' ]
    - pip_install_enable_pkg_install

- name: "{{ pip_install_task_prefix }} install pip packages: {{ pip_install_packages | join(' ') }}"
  ansible.builtin.pip:
    name: "{{ pip_install_packages }}"
    state: "{{ pip_install_state }}"
...
