---
- name: "{{ docker_task_prefix }} Install packages"
  ansible.builtin.include_role:
    name: rusops.general.pkg_install
  vars:
    pkg_install_packages: "{{ ['docker.io'] + (docker_enable_docker_compose | ternary(['docker-compose'], [])) }}"
  when:
    - docker_enable_pkg_install
    - ansible_distribution | default(undef(hint="you must gather facts before running this role")) in [ 'Ubuntu', 'Debian', 'Astra Linux' ]

- name: "{{ docker_task_prefix }} Install PIP library"
  ansible.builtin.include_role:
    name: rusops.general.pip_install
  vars:
    pip_install_packages:
      - docker
  when:
    - docker_enable_pip_install

- name: "{{ docker_task_prefix }} Customize Docker config"
  ansible.builtin.include_tasks: configure-dockerd.yml
  when:
    - docker_enable_configure

- name: "{{ docker_task_prefix }} Login to registries"
  ansible.builtin.include_tasks: docker-login.yml
  loop: "{{ docker_registry_credentials }}"
  loop_control:
    loop_var: creds
...
