---
galaxy_info:
  author: Dmitrii Kashin
  description: install and configure docker daemon
  role_name: docker
  license: MIT
  min_ansible_version: 2.12
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - docker
dependencies: []
...
